services:
  upms:
    image: quay.io/herodotus-cloud/${UPMS_SERVICE_NAME}:${VERSION}
    container_name: upms
    hostname: upms
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${UPMS_SERVICE_NAME}
        - SERVICE_PORT=${UPMS_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${UPMS_SERVICE_PORT}:${UPMS_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs

  uaa:
    image: quay.io/herodotus-cloud/${UAA_SERVICE_NAME}:${VERSION}
    container_name: uaa
    hostname: uaa
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${UAA_SERVICE_NAME}
        - SERVICE_PORT=${UAA_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${UAA_SERVICE_PORT}:${UAA_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - upms

  msg:
    image: quay.io/herodotus-cloud/${MESSAGE_SERVICE_NAME}:${VERSION}
    container_name: msg
    hostname: msg
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${MESSAGE_SERVICE_NAME}
        - SERVICE_PORT=${MESSAGE_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${MESSAGE_SERVICE_PORT}:${MESSAGE_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - uaa

  oss:
    image: quay.io/herodotus-cloud/${OSS_SERVICE_NAME}:${VERSION}
    container_name: oss
    hostname: oss
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${OSS_SERVICE_NAME}
        - SERVICE_PORT=${OSS_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${OSS_SERVICE_PORT}:${OSS_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - msg

  gateway:
    image: quay.io/herodotus-cloud/${GATEWAY_SERVICE_NAME}:${VERSION}
    container_name: gateway
    hostname: gateway
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${GATEWAY_SERVICE_NAME}
        - SERVICE_PORT=${GATEWAY_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - oss

  bpmn:
    image: quay.io/herodotus-cloud/${BPMN_SERVICE_NAME}:${VERSION}
    container_name: bpmn
    hostname: bpmn
    build:
      context: ../../../context
      dockerfile: development/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${BPMN_SERVICE_NAME}
        - SERVICE_PORT=${BPMN_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${BPMN_SERVICE_PORT}:${BPMN_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - gateway

  monitor:
    image: quay.io/herodotus-cloud/${MONITOR_SERVICE_NAME}:${VERSION}
    container_name: monitor
    hostname: monitor
    build:
      context: ../../../context
      dockerfile: development/Dockerfile-Monitor
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${MONITOR_SERVICE_NAME}
        - SERVICE_PORT=${MONITOR_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${MONITOR_SERVICE_PORT}:${MONITOR_SERVICE_PORT}
    volumes:
      - D:\\local-cached\\docker-volumes\\herodotus-cloud\\logs:/usr/local/logs
    depends_on:
      - gateway